// <auto-generated />
using ATM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATM.Data.Migrations
{
    [DbContext(typeof(AtmDbContext))]
    [Migration("20230902055259_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATM.Data.Models.CardHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("CardNum")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("CardHolders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 150.31,
                            CardNum = "4532772818527395",
                            FirstName = "John",
                            LastName = "Griffith",
                            Pin = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 321.13,
                            CardNum = "4532761841325802",
                            FirstName = "Ashley",
                            LastName = "Jones",
                            Pin = "4321"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 105.59,
                            CardNum = "5128381368581872",
                            FirstName = "Frida",
                            LastName = "Dickerson",
                            Pin = "9999"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 851.84000000000003,
                            CardNum = "6011188364697109",
                            FirstName = "Muneeb",
                            LastName = "Harding",
                            Pin = "2468"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 54.270000000000003,
                            CardNum = "3490693153147110",
                            FirstName = "Dawn",
                            LastName = "Smith",
                            Pin = "4826"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
